from pathlib import Path

PROJECT = Path(__file__).parent

INPUT_FOLDER = PROJECT / "INPUT_PDFS"
OUTPUT_FOLDER = PROJECT / "OUTPUT_DXF"
LOG_FOLDER = PROJECT / "LOGS"

DXF_VERSION = "R2018"

MIN_LINE_LENGTH = 0.001
BEZIER_SEGMENTS = 24